### ISSUE TITLE
play remote FLAC File

### ISSUE THREAD

**Issue by veso266** [audiocogs/aurora.js#185] opened 2017-04-24 20:10 UTC
Hi I would like to play this flac file: http://5.35.250.101:8000/radio700-mpx.flac but it doesn't work (with same-orogin policy turned off in chrome I get: `HEAD http://5.35.250.101:8000/radio700-mpx.flac 400 (Bad Request)`

my code is as follows: 
`<!--- Load FLAC PLAYER ----->`
`<script src="flac/aurora.js"></script>`
`<script src="flac/flac.js"></script>`
`<script>`
`var player = AV.Player.fromURL('http://5.35.250.101:8000/radio700-mpx.flac');`
`player.play();`
`</script>`

Thanks for Anwsering and Best Regards

**Comment by crackofdusk** [comment] 2017-04-25 16:30
Duplicate of https://github.com/audiocogs/flac.js/issues/31

**Closed as completed by crackofdusk** 2017-04-25 16:30 UTC
